import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Script from "next/script";

import "@/css/tailwindcss.css";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Genz App",
  description: "Generated by VIC Trade-mark",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={`${poppins.className}`}>
        {/* <Header /> */}
        {children}
        <Script
          src={"//code.tidio.co/aed6ulxqw9wemo9hgeu4ekuxjry3l6ml.js"}
          async
        ></Script>
      </body>
    </html>
  );
}
